include: package:xsoulspace_lints/app.yaml
  
analyzer:  
  errors:  
    unused_local_variable: info
    require_trailing_commas: error
    flutter_style_todos: error
    prefer_final_parameters: info
  exclude:  
    - lib/data/models
  
linter:
  rules:
    prefer_single_quotes: true 
