name: memo
description: save something in your mind
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  card_swiper : ^3.0.0
  cupertino_icons: ^1.0.2
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.4

  
dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  hive_generator: ^2.0.0
  json_serializable: ^6.9.0
  xsoulspace_lints: ^0.0.10

flutter:

  uses-material-design: true

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
  assets:        
    - assets/json/questions.json        


